apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dingo-api.fullname" . }}-secrets
  labels:
    {{- include "dingo-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | quote }}
